package com.example.st099_ghostocmaker.Model

data class GhostModel(
        val id: Int,
        val name: String,
        val accessories: ArrayList<LayerModel> = arrayListOf(),
        val armFringe: ArrayList<LayerModel> = arrayListOf(),
        val backHair: ArrayList<LayerModel> = arrayListOf(),
        val bg: ArrayList<LayerModel> = arrayListOf(),
        val bg1: ArrayList<LayerModel> = arrayListOf(),
        val blush: ArrayList<LayerModel> = arrayListOf(),
        val body: ArrayList<LayerModel> = arrayListOf(),
        val bodyPaint: ArrayList<LayerModel> = arrayListOf(),
        val charm: ArrayList<LayerModel> = arrayListOf(),
        val cloak: ArrayList<LayerModel> = arrayListOf(),
        val collar: ArrayList<LayerModel> = arrayListOf(),
        val effect: ArrayList<LayerModel> = arrayListOf(),
        val ear: ArrayList<LayerModel> = arrayListOf(),
        val eyeHoles: ArrayList<LayerModel> = arrayListOf(),
        val eyebrows: ArrayList<LayerModel> = arrayListOf(),
        val eyes: ArrayList<LayerModel> = arrayListOf(),
        val facePaint: ArrayList<LayerModel> = arrayListOf(),
        val fringe: ArrayList<LayerModel> = arrayListOf(),
        val frontHair: ArrayList<LayerModel> = arrayListOf(),
        val glass: ArrayList<LayerModel> = arrayListOf(),
        val hair: ArrayList<LayerModel> = arrayListOf(),
        val hands: ArrayList<LayerModel> = arrayListOf(),
        val hat: ArrayList<LayerModel> = arrayListOf(),
        val head: ArrayList<LayerModel> = arrayListOf(),
        val horns: ArrayList<LayerModel> = arrayListOf(),
        val horns1: ArrayList<LayerModel> = arrayListOf(),
        val lapelPin: ArrayList<LayerModel> = arrayListOf(),
        val legs: ArrayList<LayerModel> = arrayListOf(),
        val leftHand: ArrayList<LayerModel> = arrayListOf(),
        val mouth: ArrayList<LayerModel> = arrayListOf(),
        val nail: ArrayList<LayerModel> = arrayListOf(),
        val nose: ArrayList<LayerModel> = arrayListOf(),
        val other: ArrayList<LayerModel> = arrayListOf(),
        val pet: ArrayList<LayerModel> = arrayListOf(),
        val rightHand: ArrayList<LayerModel> = arrayListOf(),
        val shadow: ArrayList<LayerModel> = arrayListOf(),
        val shirt: ArrayList<LayerModel> = arrayListOf(),
        val shoes: ArrayList<LayerModel> = arrayListOf(),
        val socks: ArrayList<LayerModel> = arrayListOf(),
        val tail: ArrayList<LayerModel> = arrayListOf(),
        val whisker: ArrayList<LayerModel> = arrayListOf(),
        val wings: ArrayList<LayerModel> = arrayListOf()
)